---
- name: add motd template to server
  become: yes
  template:
    src: "{{ template_src }}"
    dest: "{{ template_dest }}"
    owner: root
    group: root
    mode: 0644
  when: (template_src is not none) or (template_dest is not none)
